name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Use latest checkout action

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4 # Use latest setup-node action
      with:
        node-version: '18.x'
        cache: 'npm' # Enable caching for npm dependencies

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test 